### ISSUE TITLE
Hyperion Cantos Wiki

### ISSUE THREAD

**Issue by abdullahkhursheed22** [abdullahkhursheed22/factsilove#44]
File name: /resources/images/hyperion-cantos-shrike.jpg
Website link: https://hyperioncantos.fandom.com/wiki/Hyperion_Cantos_Wiki
Media link: https://hyperioncantos.fandom.com/wiki/Shrike

**Comment by Hamath-Eltrael** [comment]
/resources/images/hyperion-cantos-shrike.jpg is licensed as [CC BY-SA](https://creativecommons.org/licenses/by-sa/3.0/). We can use it when we do the following for this file:
 - [ ] Attribution — You must give [appropriate credit](https://creativecommons.org/licenses/by-sa/3.0/#), provide a link to the license, and [indicate if changes were made](https://creativecommons.org/licenses/by-sa/3.0/#). You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.
- [ ] ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the [same license](https://creativecommons.org/licenses/by-sa/3.0/#) as the original.

This is true for most Images from this site, so if you have more images from here, we just have to check for `CC BY-SA` at the bottom of the article.

**Comment by Hamath-Eltrael** [comment]
If you assign me this issue I can get to those two points ad the requirements. IF you don't want to fulfil these requirements we can't use that image.


I'd go about it something like this(I can make all these decisions and just do a PullRequest and you just accept):
- [ ] Choose file format for `License` File
- [ ] Add requirements to `License` File
- [ ] Make note of `License` File in `readme.md` for this add:
- [ ] All images are licensed under Our license if that specific image is not specified in the`License` file. 
- [ ] All creators can request that we stop using their creation when they choose too if it was granted outside a License and is not stated otherwise in out agreement. This does not apply to licensed creations that we follow the license of.

**Comment by abdullahkhursheed22** [comment]
Got it. I have assigned it to you.

**Comment by Hamath-Eltrael** [comment]
We should be using `.txt` or `.md` for the License. As we are using Obsidian which is Markdown I'd say we should just continue using that. 

I also changed some formulation and made a remark of the `LICENSE` file. Why all caps? So it's easier to see. Although I think we should be able to change that if you want to. If you do, now would be the best time to do this. 

Groundwork has also been laid for all non (yet) Licensed media. 

The Pull Request #51 should solve this. Do continue to add more comments with files (and reopen) if there are more files that need attention from Hyperion Cantos Wiki.

**Comment by abdullahkhursheed22** [comment]
Awesome, thank you!

**Comment by Hamath-Eltrael** [comment]
As this is resolved, please close the issue. (See Screenshot of another issue on how) And Remember:
> Do continue to add more comments with files (and reopen[The Issue]) if there are more files that need attention from Hyperion Cantos Wiki.
